name: citytostartup
favicon: null
layout_spectrum: 0.535890961997211
typography_spectrum: 0.27675804030150175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9257263522595167
  lightness: 0.8116009545046836
  saturation: 0.39783410052768886
  rhythmicContrast: 0.04677691636607051
purpose: []
